const countries = {
  Europa: [
    { country: "Albania", capital: "Tirana" },
    { country: "Andorra", capital: "Andorra la Vella" },
    { country: "Austria", capital: "Viena" },
    { country: "Belarus", capital: "Minsk" },
    { country: "Belgia", capital: "Bruxelles" },
    { country: "Bosnia și Herțegovina", capital: "Sarajevo" },
    { country: "Bulgaria", capital: "Sofia" },
    { country: "Croația", capital: "Zagreb" },
    { country: "Cehia", capital: "Praga" },
    { country: "Danemarca", capital: "Copenhaga" },
    { country: "Estonia", capital: "Tallinn" },
    { country: "Finlanda", capital: "Helsinki" },
    { country: "Franța", capital: "Paris" },
    { country: "Germania", capital: "Berlin" },
    { country: "Grecia", capital: "Atena" },
    { country: "Ungaria", capital: "Budapesta" },
    { country: "Islanda", capital: "Reykjavik" },
    { country: "Irlanda", capital: "Dublin" },
    { country: "Italia", capital: "Roma" },
    { country: "Letonia", capital: "Riga" },
    { country: "Lituania", capital: "Vilnius" },
    { country: "Luxemburg", capital: "Luxemburg" },
    { country: "Malta", capital: "Valletta" },
    { country: "Moldova", capital: "Chișinău" },
    { country: "Monaco", capital: "Monaco" },
    { country: "Muntenegru", capital: "Podgorica" },
    { country: "Țările de Jos", capital: "Amsterdam" },
    { country: "Macedonia de Nord", capital: "Skopje" },
    { country: "Norvegia", capital: "Oslo" },
    { country: "Polonia", capital: "Varșovia" },
    { country: "Portugalia", capital: "Lisabona" },
    { country: "România", capital: "București" },
    { country: "Rusia", capital: "Moscova" },
    { country: "San Marino", capital: "San Marino" },
    { country: "Serbia", capital: "Belgrad" },
    { country: "Slovacia", capital: "Bratislava" },
    { country: "Slovenia", capital: "Ljubljana" },
    { country: "Spania", capital: "Madrid" },
    { country: "Suedia", capital: "Stockholm" },
    { country: "Elveția", capital: "Berna" },
    { country: "Turcia", capital: "Ankara" },
    { country: "Ucraina", capital: "Kiev" },
    { country: "Regatul Unit", capital: "Londra" },
    { country: "Vatican", capital: "Vatican" },
    { country: "Kosovo", capital: "Priștina" },
    { country: "Liechtenstein", capital: "Vaduz" },
    { country: "Cipru", capital: "Nicosia" },
  ],

  Asia: [
    { country: "Afganistan", capital: "Kabul" },
    { country: "Arabia Saudită", capital: "Riyadh" },
    { country: "Armenia", capital: "Erevan" },
    { country: "Azerbaidjan", capital: "Baku" },
    { country: "Bahrein", capital: "Manama" },
    { country: "Bangladesh", capital: "Dhaka" },
    { country: "Bhutan", capital: "Thimphu" },
    { country: "Brunei", capital: "Bandar Seri Begawan" },
    { country: "Cambodgia", capital: "Phnom Penh" },
    { country: "China", capital: "Beijing" },
    { country: "Coreea de Nord", capital: "Phenian" },
    { country: "Coreea de Sud", capital: "Seul" },
    { country: "Emiratele Arabe Unite", capital: "Abu Dhabi" },
    { country: "Filipine", capital: "Manila" },
    { country: "Georgia", capital: "Tbilisi" },
    { country: "India", capital: "New Delhi" },
    { country: "Indonezia", capital: "Jakarta" },
    { country: "Irak", capital: "Bagdad" },
    { country: "Iran", capital: "Teheran" },
    { country: "Israel", capital: "Ierusalim" },
    { country: "Iordania", capital: "Amman" },
    { country: "Japonia", capital: "Tokyo" },
    { country: "Kazahstan", capital: "Astana" },
    { country: "Kuweit", capital: "Kuwait City" },
    { country: "Kârgâzstan", capital: "Bishkek" },
    { country: "Laos", capital: "Vientiane" },
    { country: "Liban", capital: "Beirut" },
    { country: "Malaysia", capital: "Kuala Lumpur" },
    { country: "Maldive", capital: "Male" },
    { country: "Mongolia", capital: "Ulaanbaatar" },
    { country: "Myanmar", capital: "Naypyidaw" },
    { country: "Nepal", capital: "Kathmandu" },
    { country: "Oman", capital: "Muscat" },
    { country: "Pakistan", capital: "Islamabad" },
    { country: "Qatar", capital: "Doha" },
    { country: "Singapore", capital: "Singapore" },
    { country: "Sri Lanka", capital: "Sri Jayawardenepura Kotte" },
    { country: "Siria", capital: "Damasc" },
    { country: "Tadjikistan", capital: "Dușanbe" },
    { country: "Thailanda", capital: "Bangkok" },
    { country: "Timorul de Est", capital: "Dili" },
    { country: "Turkmenistan", capital: "Așgabat" },
    { country: "Uzbekistan", capital: "Tașkent" },
    { country: "Vietnam", capital: "Hanoi" },
    { country: "Iemen", capital: "Sana'a" },
  ],

  Africa: [
    { country: "Africa de Sud", capital: "Pretoria" },
    { country: "Algeria", capital: "Alger" },
    { country: "Angola", capital: "Luanda" },
    { country: "Benin", capital: "Porto-Novo" },
    { country: "Botswana", capital: "Gaborone" },
    { country: "Burkina Faso", capital: "Ouagadougou" },
    { country: "Burundi", capital: "Gitega" },
    { country: "Cabo Verde", capital: "Praia" },
    { country: "Camerun", capital: "Yaoundé" },
    { country: "Republica Centrafricană", capital: "Bangui" },
    { country: "Ciad", capital: "N'Djamena" },
    { country: "Comore", capital: "Moroni" },
    { country: "Congo", capital: "Brazzaville" },
    { country: "Republica Democrată Congo", capital: "Kinshasa" },
    { country: "Djibouti", capital: "Djibouti" },
    { country: "Egipt", capital: "Cairo" },
    { country: "Eritreea", capital: "Asmara" },
    { country: "Eswatini", capital: "Mbabane" },
    { country: "Etiopia", capital: "Addis Abeba" },
    { country: "Gabon", capital: "Libreville" },
    { country: "Gambia", capital: "Banjul" },
    { country: "Ghana", capital: "Accra" },
    { country: "Guineea", capital: "Conakry" },
    { country: "Guineea-Bissau", capital: "Bissau" },
    { country: "Guineea Ecuatorială", capital: "Malabo" },
    { country: "Kenya", capital: "Nairobi" },
    { country: "Lesotho", capital: "Maseru" },
    { country: "Liberia", capital: "Monrovia" },
    { country: "Libia", capital: "Tripoli" },
    { country: "Madagascar", capital: "Antananarivo" },
    { country: "Malawi", capital: "Lilongwe" },
    { country: "Mali", capital: "Bamako" },
    { country: "Mauritania", capital: "Nouakchott" },
    { country: "Mauritius", capital: "Port Louis" },
    { country: "Maroc", capital: "Rabat" },
    { country: "Mozambic", capital: "Maputo" },
    { country: "Namibia", capital: "Windhoek" },
    { country: "Niger", capital: "Niamey" },
    { country: "Nigeria", capital: "Abuja" },
    { country: "Rwanda", capital: "Kigali" },
    { country: "Sao Tome și Principe", capital: "São Tomé" },
    { country: "Senegal", capital: "Dakar" },
    { country: "Seychelles", capital: "Victoria" },
    { country: "Sierra Leone", capital: "Freetown" },
    { country: "Somalia", capital: "Mogadishu" },
    { country: "Sudan", capital: "Khartoum" },
    { country: "Sudanul de Sud", capital: "Juba" },
    { country: "Tanzania", capital: "Dodoma" },
    { country: "Togo", capital: "Lomé" },
    { country: "Tunisia", capital: "Tunis" },
    { country: "Uganda", capital: "Kampala" },
    { country: "Zambia", capital: "Lusaka" },
    { country: "Zimbabwe", capital: "Harare" },
  ],

  "America de Nord": [
    { country: "Statele Unite", capital: "Washington D.C." },
    { country: "Canada", capital: "Ottawa" },
    { country: "Mexic", capital: "Ciudad de Mexico" },
    { country: "Cuba", capital: "Havana" },
    { country: "Jamaica", capital: "Kingston" },
    { country: "Haiti", capital: "Port-au-Prince" },
    { country: "Republica Dominicană", capital: "Santo Domingo" },
    { country: "Bahamas", capital: "Nassau" },
    { country: "Barbados", capital: "Bridgetown" },
    { country: "Belize", capital: "Belmopan" },
    { country: "Costa Rica", capital: "San José" },
    { country: "El Salvador", capital: "San Salvador" },
    { country: "Guatemala", capital: "Guatemala City" },
    { country: "Honduras", capital: "Tegucigalpa" },
    { country: "Nicaragua", capital: "Managua" },
    { country: "Panama", capital: "Panama City" },
    { country: "Trinidad și Tobago", capital: "Port of Spain" },
  ],

  "America de Sud": [
    { country: "Argentina", capital: "Buenos Aires" },
    { country: "Bolivia", capital: "Sucre" },
    { country: "Brazilia", capital: "Brasilia" },
    { country: "Chile", capital: "Santiago" },
    { country: "Columbia", capital: "Bogota" },
    { country: "Ecuador", capital: "Quito" },
    { country: "Guyana", capital: "Georgetown" },
    { country: "Paraguay", capital: "Asuncion" },
    { country: "Peru", capital: "Lima" },
    { country: "Surinam", capital: "Paramaribo" },
    { country: "Uruguay", capital: "Montevideo" },
    { country: "Venezuela", capital: "Caracas" },
  ],

  Oceania: [
    { country: "Australia", capital: "Canberra" },
    { country: "Fiji", capital: "Suva" },
    { country: "Kiribati", capital: "Tarawa" },
    { country: "Marshall", capital: "Majuro" },
    { country: "Micronezia", capital: "Palikir" },
    { country: "Nauru", capital: "Yaren" },
    { country: "Noua Zeelandă", capital: "Wellington" },
    { country: "Palau", capital: "Ngerulmud" },
    { country: "Papua Noua Guinee", capital: "Port Moresby" },
    { country: "Samoa", capital: "Apia" },
    { country: "Solomon", capital: "Honiara" },
    { country: "Tonga", capital: "Nuku'alofa" },
    { country: "Tuvalu", capital: "Funafuti" },
    { country: "Vanuatu", capital: "Port Vila" },
  ],
};

export default countries;
